import { useState, type PropsWithChildren } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import type { ScryfallCard } from '../types/mtg';
import { colors } from '../theme';

export function Screen({ children }: PropsWithChildren) { return <ScrollView contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled">{children}</ScrollView>; }
export function Title({ children, subtitle }: PropsWithChildren<{ subtitle?: string }>) { return <View style={styles.titleWrap}><Text style={styles.title}>{children}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>; }
export function Input(props: TextInputProps) { return <TextInput placeholderTextColor={colors.muted} {...props} style={[styles.input, props.multiline && styles.multiline, props.style]} />; }
export function Button({ title, onPress, disabled, secondary = false }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.buttonSecondary, disabled && styles.disabled]}><Text style={[styles.buttonText, secondary && styles.buttonTextSecondary]}>{title}</Text></Pressable>; }
export function CardRow({ card, action, actionLabel }: { card: ScryfallCard; action?: () => void; actionLabel?: string }) {
  const storedImages = card.imageUrls?.length ? card.imageUrls : card.imageUrl ? [card.imageUrl] : [];
  const fallbackImage = card.id ? `https://api.scryfall.com/cards/${encodeURIComponent(card.id)}?format=image&version=normal` : undefined;
  const images = storedImages.length ? storedImages : fallbackImage ? [fallbackImage] : [];
  const [face, setFace] = useState(0); const [failed, setFailed] = useState(false); const [details, setDetails] = useState(false); const imageUrl = images[face];
  const cycleFace = () => { if (images.length > 1) { setFailed(false); setFace((current) => (current + 1) % images.length); } };
  return <View style={styles.cardWrap}><View style={styles.cardRow}><Pressable onPress={cycleFace} disabled={images.length < 2} style={styles.cardImageWrap}>{imageUrl && !failed ? <Image source={{ uri: imageUrl }} style={styles.cardImage} resizeMode="cover" onError={() => setFailed(true)} /> : <View style={[styles.cardImage, styles.cardImageFallback]}><Text style={styles.cardImageFallbackText}>Art unavailable</Text></View>}{images.length > 1 ? <Text style={styles.faceBadge}>{face + 1}/{images.length}</Text> : null}</Pressable><View style={styles.cardInfo}><View style={styles.row}><Text numberOfLines={2} style={styles.cardName}>{card.name}</Text><Text style={styles.mana}>{card.manaCost ?? ''}</Text></View><Text style={styles.meta}>{card.typeLine}</Text><Text style={styles.meta}>{card.set} · #{card.collectorNumber}</Text><Text style={styles.price}>{card.usdPrice ? '$' + card.usdPrice + ' USD' : 'USD price unavailable'}</Text>{images.length > 1 ? <Text style={styles.faceHint}>Tap art to flip card</Text> : null}<Pressable onPress={() => setDetails((value) => !value)}><Text style={styles.detailAction}>{details ? 'Hide details' : 'Card details'}</Text></Pressable>{action ? <Pressable onPress={action}><Text style={styles.action}>{actionLabel}</Text></Pressable> : null}</View></View>{details ? <View style={styles.details}><Text style={styles.detailTitle}>{card.setName}</Text><Text style={styles.detailText}>{card.oracleText?.trim() || 'No oracle text.'}</Text><Text style={styles.detailMeta}>Commander: {card.commanderLegality.replace('_', ' ')} · Color identity: {card.colorIdentity.join('') || 'Colorless'}</Text></View> : null}</View>;
}
export function Loading() { return <ActivityIndicator color={colors.gold} size="large" />; }
export const ui = StyleSheet.create({ panel: { backgroundColor: colors.panel, borderColor: colors.border, borderRadius: 14, borderWidth: 1, marginBottom: 12, padding: 15 }, label: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1, marginBottom: 7, textTransform: 'uppercase' }, text: { color: colors.text, fontSize: 15, lineHeight: 22 }, muted: { color: colors.muted, fontSize: 14, lineHeight: 20 }, heading: { color: colors.text, fontSize: 18, fontWeight: '700', marginBottom: 10 }, row: { alignItems: 'center', flexDirection: 'row', gap: 8 }, error: { color: colors.red, marginBottom: 8 }, success: { color: colors.green, marginBottom: 8 } });
const styles = StyleSheet.create({
  screen: { padding: 18, paddingBottom: 36 }, titleWrap: { marginBottom: 18 }, title: { color: colors.text, fontSize: 28, fontWeight: '800' }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 5 }, input: { backgroundColor: colors.panel, borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, fontSize: 15, marginBottom: 10, paddingHorizontal: 13, paddingVertical: 11 }, multiline: { minHeight: 100, textAlignVertical: 'top' }, button: { alignItems: 'center', backgroundColor: colors.gold, borderRadius: 10, marginBottom: 10, paddingHorizontal: 14, paddingVertical: 12 }, buttonSecondary: { backgroundColor: colors.panelRaised, borderColor: colors.border, borderWidth: 1 }, buttonText: { color: '#080b10', fontSize: 14, fontWeight: '800' }, buttonTextSecondary: { color: colors.text }, disabled: { opacity: 0.45 },
  cardWrap: { backgroundColor: colors.panel, borderColor: colors.border, borderRadius: 12, borderWidth: 1, marginBottom: 10, overflow: 'hidden' }, cardRow: { flexDirection: 'row' }, cardImageWrap: { height: 154, width: 110 }, cardImage: { backgroundColor: colors.panelRaised, height: 154, width: 110 }, cardImageFallback: { alignItems: 'center', justifyContent: 'center', padding: 10 }, cardImageFallbackText: { color: colors.muted, fontSize: 11, textAlign: 'center' }, faceBadge: { backgroundColor: 'rgba(8,11,16,0.8)', borderRadius: 8, bottom: 6, color: colors.text, fontSize: 10, fontWeight: '800', paddingHorizontal: 6, paddingVertical: 3, position: 'absolute', right: 6 }, cardInfo: { flex: 1, padding: 11 }, row: { flexDirection: 'row', justifyContent: 'space-between' }, cardName: { color: colors.text, flex: 1, fontSize: 16, fontWeight: '700', marginRight: 8 }, mana: { color: colors.blue, fontSize: 13 }, meta: { color: colors.muted, fontSize: 12, marginTop: 5 }, price: { color: colors.green, fontSize: 12, fontWeight: '700', marginTop: 7 }, faceHint: { color: colors.blue, fontSize: 11, marginTop: 6 }, detailAction: { color: colors.blue, fontSize: 12, fontWeight: '700', marginTop: 8 }, action: { color: colors.gold, fontSize: 13, fontWeight: '800', marginTop: 8 }, details: { borderTopColor: colors.border, borderTopWidth: 1, padding: 12 }, detailTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginBottom: 7 }, detailText: { color: colors.text, fontSize: 13, lineHeight: 19 }, detailMeta: { color: colors.muted, fontSize: 11, marginTop: 9, textTransform: 'capitalize' },
});