import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Button, Input, Loading, Screen, Title, ui } from '../components/ui';
import { useVault } from '../context/VaultContext';
import type { CoachRecommendation } from '../types/mtg';
import { validateCommanderDeck } from '../utils/deck';

const API_URL = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000';
export function AiCoachScreen() {
  const { decks } = useVault(); const [deckId, setDeckId] = useState(''); const [instructions, setInstructions] = useState('Optimize this for bracket 3 under $50.'); const [result, setResult] = useState<CoachRecommendation>(); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const deck = decks.find((item) => item.id === deckId);
  const coach = async () => { if (!deck) return; setLoading(true); setError(''); setResult(undefined); try { const response = await fetch(`${API_URL}/api/coach`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ instructions, deck: { name: deck.name, commander: deck.commander, cards: deck.cards, validation: validateCommanderDeck(deck) } }) }); const body = await response.json() as CoachRecommendation | { error: string }; if (!response.ok) throw new Error('error' in body ? body.error : 'Coach request failed.'); setResult(body as CoachRecommendation); } catch (value) { setError(value instanceof Error ? value.message : 'Coach request failed.'); } finally { setLoading(false); } };
  return <Screen><Title subtitle="Get structured upgrade ideas. Suggestions are advisory—review before changing your deck.">AI Coach</Title><Text style={ui.label}>Select a deck</Text><View style={[ui.row, { flexWrap: 'wrap', marginBottom: 12 }]}>{decks.map((item) => <Pressable key={item.id} onPress={() => setDeckId(item.id)} style={[ui.panel, { padding: 10 }, item.id === deckId && { borderColor: '#d6aa5d' }]}><Text style={ui.text}>{item.name}</Text></Pressable>)}</View><Input multiline value={instructions} onChangeText={setInstructions} placeholder="Optimize this for bracket 3 under $50." />{loading ? <Loading /> : <Button title="Ask AI Coach" onPress={() => void coach()} disabled={!deck || !instructions.trim()} />}{error ? <Text style={ui.error}>{error}</Text> : null}
    {result ? <><View style={ui.panel}><Text style={ui.label}>Summary</Text><Text style={ui.text}>{result.summary}</Text>{result.needsReview ? <Text style={ui.error}>Some card names could not be validated with Scryfall. Review flagged results.</Text> : null}</View><ResultList title="Strengths" values={result.strengths} /><ResultList title="Weaknesses" values={result.weaknesses} /><ResultList title="Strategy" values={result.strategy} /><View style={ui.panel}><Text style={ui.heading}>Suggested cuts</Text>{result.suggestedCuts.map((item) => <Text key={item.name} style={ui.text}>• {item.name} — {item.reason}</Text>)}</View><View style={ui.panel}><Text style={ui.heading}>Suggested adds</Text>{result.suggestedAdds.map((item) => <Text key={item.name} style={item.validated ? ui.text : ui.error}>• {item.name} {item.validated ? '✓' : '⚠ needs review'} — {item.reason}</Text>)}</View><ResultList title="Warnings" values={result.warnings} /></> : null}</Screen>;
}
function ResultList({ title, values }: { title: string; values: string[] }) { return <View style={ui.panel}><Text style={ui.heading}>{title}</Text>{values.length ? values.map((value, index) => <Text key={`${value}-${index}`} style={ui.text}>• {value}</Text>) : <Text style={ui.muted}>None noted.</Text>}</View>; }
