import { useMemo, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { AiBuildPanel } from '../components/AiBuildPanel';
import { Button, CardRow, Input, Loading, Screen, Title, ui } from '../components/ui';
import { useVault } from '../context/VaultContext';
import { searchCards } from '../services/scryfall';
import type { DeckCardEntry, ScryfallCard } from '../types/mtg';
import { canBeCommander, replaceCommander, upsertCard, validateCommanderDeck } from '../utils/deck';
const groupName=(entry:DeckCardEntry)=>{const t=entry.card.typeLine;if(t.includes('Creature'))return'Creatures';if(t.includes('Land'))return'Lands';if(t.includes('Artifact'))return'Artifacts';if(t.includes('Enchantment'))return'Enchantments';if(t.includes('Planeswalker'))return'Planeswalkers';if(t.includes('Instant'))return'Instants';if(t.includes('Sorcery'))return'Sorceries';return'Other';};
const GROUPS=['Creatures','Artifacts','Enchantments','Planeswalkers','Instants','Sorceries','Lands','Other'];
export function BuildScreen() {
 const {decks,updateDeck}=useVault(); const [deckId,setDeckId]=useState(''); const [query,setQuery]=useState(''); const [results,setResults]=useState<ScryfallCard[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const deck=decks.find((item)=>item.id===deckId); const validation=useMemo(()=>deck?validateCommanderDeck(deck):undefined,[deck]);
 const grouped=useMemo(()=>deck?GROUPS.map((name)=>({name,entries:deck.cards.filter((entry)=>groupName(entry)===name)})).filter((group)=>group.entries.length):[],[deck]);
 const stats=useMemo(()=>{if(!deck)return undefined;const lands=deck.cards.filter((e)=>e.card.typeLine.includes('Land')).reduce((s,e)=>s+e.quantity,0);const creatures=deck.cards.filter((e)=>e.card.typeLine.includes('Creature')).reduce((s,e)=>s+e.quantity,0);const value=deck.cards.reduce((s,e)=>s+(Number(e.card.usdPrice)||0)*e.quantity,Number(deck.commander?.usdPrice)||0);return{lands,creatures,value};},[deck]);
 const search=async()=>{if(!query.trim())return;setLoading(true);setError('');try{setResults(await searchCards(query));}catch(value){setError(value instanceof Error?value.message:'Search failed.');}finally{setLoading(false);}};
 const add=(card:ScryfallCard)=>{if(deck)updateDeck({...deck,cards:upsertCard(deck.cards,card)});};
 return <Screen><Title subtitle="Build, inspect, and validate a Commander deck with live Scryfall data.">Build</Title><AiBuildPanel/><Text style={ui.label}>Choose deck</Text><View style={[ui.row,{flexWrap:'wrap',marginBottom:14}]}>{decks.map((item)=><Pressable key={item.id} onPress={()=>setDeckId(item.id)} style={[ui.panel,{padding:10},item.id===deckId&&{borderColor:'#d6aa5d'}]}><Text style={ui.text}>{item.name}</Text></Pressable>)}</View>
 {!deck?<Text style={ui.muted}>Create and select a deck to start building.</Text>:<><View style={ui.panel}><Text style={ui.label}>Commander</Text>{deck.commander?<CardRow card={deck.commander}/>:<Text style={ui.heading}>Not selected</Text>}<Text style={ui.heading}>{validation?.totalCards??0}/100 cards</Text><Text style={validation?.isValid?ui.success:ui.error}>{validation?.isValid?'Commander checks pass.':(validation?.issues.length??0)+' issue(s) to resolve.'}</Text>{validation?.issues.slice(0,5).map((issue,index)=><Text key={(issue.cardName??'deck')+'-'+index} style={ui.muted}>• {issue.message}</Text>)}</View>
 {stats?<View style={ui.panel}><Text style={ui.label}>Deck statistics</Text><Text style={ui.text}>Creatures {stats.creatures} · Lands {stats.lands} · Other cards {(validation?.totalCards??0)-stats.creatures-stats.lands}</Text><Text style={ui.text}>Tracked card value: ${stats.value.toFixed(2)} USD</Text></View>:null}
 <Input value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} placeholder="Search Scryfall to add cards"/><Button title="Search" onPress={()=>void search()}/>{error?<Text style={ui.error}>{error}</Text>:null}{loading?<Loading/>:results.map((card)=><CardRow key={card.id} card={card} action={()=>add(card)} actionLabel="+ Add to deck"/>)}
 <Text style={ui.heading}>Deck cards</Text>{deck.cards.length===0?<Text style={ui.muted}>No cards added yet.</Text>:grouped.map((group)=><View key={group.name}><Text style={ui.label}>{group.name} · {group.entries.reduce((sum,entry)=>sum+entry.quantity,0)}</Text>{group.entries.map((entry)=><View key={entry.card.id}><CardRow card={entry.card}/><Text style={ui.muted}>Quantity: {entry.quantity}</Text><View style={ui.row}><Button title="−" secondary onPress={()=>updateDeck({...deck,cards:upsertCard(deck.cards,entry.card,-1)})}/><Button title="+" secondary onPress={()=>add(entry.card)}/>{canBeCommander(entry.card)?<Button title="Set commander" onPress={()=>updateDeck(replaceCommander(deck,entry.card))}/>:null}</View></View>)}</View>)}</>}</Screen>;
}